name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: git clone
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: vet
      run: go vet ./...
