name: Test

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: go mod tidy -x
        run: go mod tidy -x
      - name: go vet ./...
        run: go vet ./...
      - name: go test -v ./...
        run: go test -v ./...
      - name: go build -v ./...
        run: go build -v ./...
